/**
 * Created by Jack.Wang on 14-7-24.
 */

exports.USER_ENABLE_STATUS=0;
exports.USER_UNABLE_STATUS=1;
exports.USER_DELETE_STATUS=2;

exports.CATEGORY_ENABLE_STATUS=0;
exports.CATEGORY_UNABLE_STATUS=1;

exports.COMMENT_ENABLE_STATUS=0;
exports.COMMENT_UNABLE_STATUS=1;

exports.CONTENT_ENABLE_STATUS=0;
exports.CONTENT_UNABLE_STATUS=1;
exports.CONTENT_SELF_STATUS=2;

exports.LOG_ENABLE_STATUS=0;
exports.LOG_UNABLE_STATUS=1;

exports.PER_PAGE_COUNT = 9;